### PR TITLE
Fix build and test workflow

### LINKED ISSUE #24: Testing workflow is broken
The current build and test workflow that I wrote is broken in a few regards.
- It only tests MinGW on Windows.
- Linux and macOS install outdated Meson and Ninja versions
- Meson and ninja versions are not fixed
- Some other major issues that I forgot.

### PR DESCRIPTION
**Pull request by Sophon96**
Fixes #24.

### CODE REVIEW

**Comment by Sophon96** [comment]
I wonder why it still finds gcc instead of msvc.

**Comment by Sophon96** [comment]
Looks like it works now!

**Comment by adamhutchings** [comment]
@Sophon96 can we merge this?

**Comment by Sophon96** [comment]
> @Sophon96 can we merge this?

Yes!

**Pull request merged**
