### PR TITLE
Fix workflow on Windows by switching meson install method

### LINKED ISSUE #15: Fix workflow on Windows

### PR DESCRIPTION
**Pull request by Sophon96**

### CODE REVIEW

**Comment by Sophon96** [comment]
HUHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH????????????????????????????????

**Comment by Sophon96** [comment]
lemme pop open windows sandbox for this rq

**Comment by Sophon96** [comment]
Now this is just AMAZING!
image

**Comment by Sophon96** [comment]
LETS F-ING GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Review by JakeRoggenbuck — APPROVED** [review]
Nice!

**Review by adamhutchings — APPROVED** [review]

**Pull request merged**
